# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

arr1.ndim,arr2.ndim,arr3.ndim

(1, 2, 3)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
arr1.shape,arr1.ndim,arr1.dtype,arr1.size,type(arr1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
arr2.shape,arr2.ndim,arr2.dtype,arr2.size,type(arr2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
arr3.shape,arr3.ndim,arr3.dtype,arr3.size,type(arr3)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(arr2)
df

0  1  2
0  1  2  3
1  4  5  6

In [7]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
arr4 = np.arange(0,100,step=3)
arr4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_arr = np.random.randint(0,10,size=(7,2))
rand_arr

array([[7, 6],
       [6, 6],
       [3, 9],
       [9, 0],
       [2, 5],
       [3, 6],
       [1, 2]])

In [14]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand_arr2 = np.random.random((3,5))
rand_arr2

array([[0.6584745 , 0.59764199, 0.76577424, 0.71671346, 0.24574263],
       [0.27907412, 0.00702734, 0.43386218, 0.21099752, 0.15287758],
       [0.50076872, 0.79125968, 0.23612217, 0.5442456 , 0.13746777]])

In [16]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rand_arr3 = np.random.randint(0,10,size=(4,6))
rand_arr3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [19]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

arr5 = np.random.randint(1,10,size=(3,7))
# Find the unique numbers in the array you just created
arr5,np.unique(arr5)

(array([[2, 5, 8, 9, 9, 1, 9],
        [7, 9, 8, 1, 8, 8, 3],
        [1, 8, 3, 3, 1, 5, 7]]),
 array([1, 2, 3, 5, 7, 8, 9]))

In [21]:
# Find the 0'th index of the latest array you created
arr5[0][0]

np.int64(2)

In [22]:
# Get the first 2 rows of latest array you created
arr5[:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [23]:
# Get the first 2 values of the first 2 rows of the latest array
arr5[:2,:2]

array([[2, 5],
       [7, 9]])

In [28]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr6 = np.random.randint(0,10,size=(3,5))
arr7 = np.ones((3,5))

In [33]:
# Add the two arrays together
arr8=np.add(arr6,arr7)
arr8

array([[ 1.,  3.,  5.,  3.,  1.],
       [ 5., 10.,  7.,  7.,  9.],
       [10., 10.,  3.,  7.,  1.]])

In [34]:
# Create another array of ones of shape (5, 3)
arr9 = np.ones((5,3))

In [35]:
# Try add the array of ones and the other most recent array together
arr8+arr9

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [37]:
# Create another array of ones of shape (3, 5)
arr10 = np.ones((3,5))
arr10

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
# Subtract the new array of ones from the other most recent array
arr11 = arr8-arr10
arr11

array([[0., 2., 4., 2., 0.],
       [4., 9., 6., 6., 8.],
       [9., 9., 2., 6., 0.]])

In [42]:
# Multiply the ones array with the latest array
arr12 = arr10*arr11
arr12

array([[0., 2., 4., 2., 0.],
       [4., 9., 6., 6., 8.],
       [9., 9., 2., 6., 0.]])

In [43]:
# Take the latest array to the power of 2 using '**'
arr12 **2

array([[ 0.,  4., 16.,  4.,  0.],
       [16., 81., 36., 36., 64.],
       [81., 81.,  4., 36.,  0.]])

In [47]:
# Do the same thing with np.square()
arr13=np.square(arr12)
arr13

array([[ 0.,  4., 16.,  4.,  0.],
       [16., 81., 36., 36., 64.],
       [81., 81.,  4., 36.,  0.]])

In [48]:
# Find the mean of the latest array using np.mean()
np.mean(arr13)

np.float64(30.6)

In [49]:
# Find the maximum of the latest array using np.max()
np.max(arr13)

np.float64(81.0)

In [50]:
# Find the minimum of the latest array using np.min()
np.min(arr13)

np.float64(0.0)

In [51]:
# Find the standard deviation of the latest array
np.std(arr13)

np.float64(30.748008065564182)

In [52]:
# Find the variance of the latest array
np.var(arr13)

np.float64(945.44)

In [53]:
# Reshape the latest array to (3, 5, 1)
arr14 = np.reshape(arr13,(3,5,1))
arr14

array([[[ 0.],
        [ 4.],
        [16.],
        [ 4.],
        [ 0.]],

       [[16.],
        [81.],
        [36.],
        [36.],
        [64.]],

       [[81.],
        [81.],
        [ 4.],
        [36.],
        [ 0.]]])

In [54]:
# Transpose the latest array
arr14.T

array([[[ 0., 16., 81.],
        [ 4., 81., 81.],
        [16., 36.,  4.],
        [ 4., 36., 36.],
        [ 0., 64.,  0.]]])

What does the transpose do?

In [55]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a1 = np.random.randint(0,10,size=(3,3))
a2 = np.random.randint(0,10,size=(3,2))

In [56]:
# Perform a dot product on the two newest arrays you created
np.dot(a1,a2)

array([[47, 51],
       [69, 87],
       [47, 77]])

In [57]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a3=np.random.randint(0,10,size=(4,3))
a4=np.random.randint(0,10,size=(4,3))

In [58]:
# Perform a dot product on the two newest arrays you created
np.dot(a3,a4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [59]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
a4_transpose = a4.T
np.dot(a3,a4_transpose)

array([[151,  52, 163, 135],
       [ 30,  24,  54,  42],
       [120,  38, 143, 129],
       [102,  44, 116,  90]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [60]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a5=np.random.randint(0,10,size=(3,3))
a6=np.random.randint(0,10,size=(3,3))
a5,a6

(array([[0, 0, 9],
        [3, 6, 1],
        [2, 0, 4]]),
 array([[0, 7, 0],
        [0, 1, 1],
        [5, 6, 4]]))

In [61]:
# Compare the two arrays with '>'
a5>a6

array([[False, False,  True],
       [ True,  True, False],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [62]:
# Compare the two arrays with '>='
a5>=a6

array([[ True, False,  True],
       [ True,  True,  True],
       [False, False,  True]])

In [63]:
# Find which elements of the first array are greater than 7
a5>7

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [64]:
# Which parts of each array are equal? (try using '==')
a5==a6

array([[ True, False, False],
       [False, False,  True],
       [False, False,  True]])

In [65]:
# Sort one of the arrays you just created in ascending order
a5,np.sort(a5)

(array([[0, 0, 9],
        [3, 6, 1],
        [2, 0, 4]]),
 array([[0, 0, 9],
        [1, 3, 6],
        [0, 2, 4]]))

In [66]:
# Sort the indexes of one of the arrays you just created
np.argsort(a5)

array([[0, 1, 2],
       [2, 0, 1],
       [1, 0, 2]])

In [68]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a5,axis=1)

array([2, 1, 2])

In [69]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a5,axis=1)

array([0, 2, 1])

In [70]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a5,axis=1)

array([2, 1, 2])

In [71]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a5,axis=0)

array([0, 0, 1])

In [72]:
# Create an array of normally distributed random numbers
a6=np.random.randn(3,5)
a6

array([[ 1.23701607, -1.42647888,  0.33802266,  1.9745712 ,  1.96503476],
       [-1.93991122, -0.76262696,  0.16865939, -1.32187695, -0.6682467 ],
       [-0.137291  ,  1.40132156, -0.04540266,  0.21693673,  0.51242373]])

In [76]:
# Create an array with 10 evenly spaced numbers between 1 and 100
a7=np.linspace(1,100,10)
a7

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.

In [74]:
a8 = np.arange(0,100,10)
a8

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])